server:
  address: 0.0.0.0
  port: 9100

welcome:
  message: local dev profile for gateway server

spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages/messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  application:
    name: gateway

  #spring 默认的json序列化, 设置时区与日期格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  #jmx远程管理
  jmx:
    enabled: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # 服务名小写

#      routes:
#        - id: demo-service
#          # lb代表从注册中心获取服务，且已负载均衡方式转发
#          uri: lb://demo-service   #注册中心的服务名称
#          predicates:
#            - Path=/demo/**    #匹配的请求路由
#            # 加上StripPrefix=1，否则转发到后端服务时会带上consumer前缀
#          filters:
#            - StripPrefix=1


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.16.114.245:10010/eureka/

    #eureka client刷新本地缓存时间
    #默认30s
    registry-fetch-interval-seconds: 5
ribbon:
  server-list-refresh-interval: 3000 # Ribbon更新周期

# 远程管理,暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


app:
  filter:
    extract-request-params: true     #是否提取请求参数， 上线u若影响性能可以关闭
    extract-response-body: true      #是否提取响应体， 上线u若影响性能可以关闭
    enable-token-auth: true          #是否开启token验证
    enable-token-auth-check-cache: true          #是否token必须存在网关缓存中
    token-auth-ignore-path: /actuator,/actuator/*,/hello,/login,/loginOut,/refreshToken #忽略token验证的路由path， 多个path使用逗号分隔
  token:
    expire-minutes: 300   #token过期时间（分钟）
    sign-key: ezml-sign-key  #token生成使用的加密密钥
  service:
    user-service: USER-SERVICE  #用户服务的注册名称
    user-service-api: /user/getUserInfo  #用户服务的接口地址
#    user-service: DEMO  #用户服务的注册名称
#    user-service-api: /getUserInfo  #用户服务的接口地址

