server:
  port: 10020

spring:
  application:
    name: demo    #服务注册的名称
  servlet:
    multipart:
      max-file-size:  500MB
      max-request-size: 500MB

eureka:
  instance:
    prefer-ip-address: true #优先使用ip地址注册
    lease-renewal-interval-in-seconds: 5  #表示eureka client发送心跳给server端的频率
    lease-expiration-duration-in-seconds: 5   #等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
  client:
    # 指示到eureka服务器的HTTP连接在关闭之前可以保持空闲的时间(以秒为单位)
    eureka-connection-idle-timeout-seconds: 3
    healthcheck:  #健康检查， 如果启用该配置， 则需要引入 spring-boot-starter-actuator
      enabled: true
    service-url:  #eureka server的地址
      defaultZone: http://127.0.0.1:10010/eureka/


# 远程管理,暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# API docs
springdoc:
  api-docs:
    enabled: true
    path: /apidocs
  swagger-ui:
    path: /swagger-ui.html

