server:
  port: 9100

spring:
  profiles:
    active: master
  application:
    name: eureka

# 远程管理,暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

eureka-cluster-register:
  ip: localhost
  port: ${server.port}


eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka-cluster-register.ip}:${eureka-cluster-register.port}/eureka/







